version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - "@The-Bds-Maneger/mainteners"
    reviewers:
      - "@The-Bds-Maneger/mainteners"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    assignees:
      - "@The-Bds-Maneger/mainteners"
    reviewers:
      - "@The-Bds-Maneger/mainteners"