name: Build binarys
on:
  push:
    branches:
      - "main"

env:
  NODE_VERSION: "18"

jobs:
  # Build Bin to MacOS, Linux And Windows
  build_nix:
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os == 'ubuntu-latest' && 'Linux' || matrix.os == 'windows-latest' && 'Windows' || 'MacOS' }} binary build"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "${{ env.NODE_VERSION }}.x"

      - name: Set up NASM (Windows only)
        if: matrix.os == 'windows-latest'
        uses: ilammy/setup-nasm@v1.3.1

      - name: Install dependencies
        run: npm ci

      - name: Transpiler TypeScript
        run: npm run build

      - name: Cache nexe
        uses: actions/cache@v3
        with:
          key: "${{ matrix.os }}_nexe-build_${{ env.NODE_VERSION }}"
          path: |
            ~/.nexe
            ~\.nexe
            %HOMEDIR%\.nexe

      - name: Build Binary file
        continue-on-error: true
        run: npm run build:bin -- --verbose

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os == 'ubuntu-latest' && 'Linux' || matrix.os == 'windows-latest' && 'Windows' || 'MacOS' }}_${{ runner.arch }}_${{ env.NODE_VERSION }}
          path: BdsManegerCLI_*

  # Build for Linux and Android (arm64)
  build_linux_arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - linux
          # - android
    name: "${{ matrix.target == 'linux' && 'Linux' || 'Android' }} binary build for Arm64 arch"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "${{ env.NODE_VERSION }}.x"

      - name: Install host build
        run: |
          sudo apt update
          sudo apt install -y binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install dependencies
        run: npm ci

      - name: Transpiler Typescript
        run: npm run build

      - name: Cache nexe
        uses: actions/cache@v3
        with:
          key: "${{ matrix.target }}_nexe-build_${{ env.NODE_VERSION }}"
          path: ~/.nexe

      - name: Build Binary file
        continue-on-error: true
        run: npm run build:bin -- --Arch=arm64 --Platform=${{ matrix.target }}
        env:
          CXX_host: "g++"
          CC_host: "gcc"
          CXX: aarch64-linux-gnu-g++
          CC: aarch64-linux-gnu-gcc

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}_${{ env.NODE_VERSION }}
          path: BdsManegerCLI_*
