name: Build binarys
on:
  push:
    branches:
      - "main"

env:
  NODE_VERSION: "18"

jobs:
  # Build Bin to MacOS and Linux
  build_nix:
    runs-on: ${{ matrix.os }}
    name: (MacOS/Linux) Build binary (${{ matrix.os }})
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      
      - uses: actions/setup-node@v3.1.1
        name: Setup Node.js
        with:
          node-version: "${{ env.NODE_VERSION }}.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Cache nexe
        uses: actions/cache@v3
        with:
          path: ~/.nexe
          key: "${{ matrix.os }}_${{ github.ref }}_${{ github.repo }}_${{ env.NODE_VERSION }}"

      - name: Build binary
        run: npm run build:bin

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}_${{ env.NODE_VERSION }}
          path: bin_*