name: Build binarys
on:
  push:
    branches:
      - "main"

env:
  NODE_VERSION: "18"

jobs:
  # Build Bin to MacOS, Linux And Windows
  build_nix:
    runs-on: ${{ matrix.os }}
    name: "(Os: ${{ matrix.os == 'ubuntu-latest' && 'Linux' || matrix.os == 'windows-latest' && 'Windows' || 'MacOS' }}, Arch: ?) Build binary"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.2.0
        with:
          node-version: "${{ env.NODE_VERSION }}.x"

      - name: Set up NASM (Windows only)
        if: matrix.os == 'windows-latest'
        uses: ilammy/setup-nasm@v1.3.0

      - name: Install dependencies
        run: npm ci

      - name: Transpiler TypeScript
        run: npm run build

      - name: Cache nexe
        uses: actions/cache@v3
        with:
          key: "${{ matrix.os }}_nexe-build_${{ env.NODE_VERSION }}"
          path: |
            ~/.nexe
            ~\.nexe
            %HOMEDIR%\.nexe

      - name: Build Binary file
        run: npm run build:bin

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os == 'ubuntu-latest' && 'Linux' || 'MacOS' }}_${{ runner.arch }}_${{ env.NODE_VERSION }}
          path: BdsManegerCLI_*

  # Build for Linux and Android (arm64)
  build_linux_arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - linux-arm64
          - android-arm64
    name: "(Os: ${{ matrix.target == 'linux-arm64' && 'Linux' || 'Android' }}, Arch: Arm64/aarch64) Build binary"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.2.0
        with:
          node-version: "${{ env.NODE_VERSION }}.x"

      - name: Install host build
        run: |
          sudo apt update
          sudo apt install -y binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install dependencies
        run: npm ci

      - name: Transpiler Typescript
        run: npm run build

      - name: Cache nexe
        uses: actions/cache@v3
        with:
          key: "${{ matrix.target }}_nexe-build_${{ env.NODE_VERSION }}"
          path: ~/.nexe

      - name: Build Binary file
        run: npm run build:bin -- --target=${{ matrix.target }} --verbose --config_args="${{ matrix.target == 'linux-arm64' && env.LINUXARMCO || env.ANDROIDCON }}"
        env:
          LINUXARMCO: "--cross-compiling,--dest-os=linux,--with-arm-float-abi=hard,--with-arm-fpu=neon"
          ANDROIDCON: "--dest-cpu=arm64,--dest-os=android,--shared-cares,--shared-openssl,--shared-zlib,--cross-compiling"
          CXX_host: "g++"
          CC_host: "gcc"
          CXX: aarch64-linux-gnu-g++
          CC: aarch64-linux-gnu-gcc

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}_${{ env.NODE_VERSION }}
          path: BdsManegerCLI_*