name: Publish release module release
on:
  release:
    types:
      - created

jobs:
  publishreleasemodule:
    runs-on: ubuntu-latest
    name: Publish npm module (release)
    strategy:
      matrix:
        npm_registry:
          - "Github"
          - "NPM"
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Setup Node.js (NPM Packages)
        if: matrix.npm_registry == 'NPM'
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Setup Node.js (Github Packages)
        if: matrix.npm_registry == 'Github'
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/

      - name: Install node depencies
        run: npm install -d

      - name: Build typescript to CJS and ESM
        run: npm run build

      - name: Publish Package
        run: |
          set -x
          if [[ "${{ matrix.npm_registry }}" == "Github" ]];then
            echo "Publish to Github Packages"
            export NODE_AUTH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          else
            echo "Publish to NPM Registry"
            export NODE_AUTH_TOKEN="${{ secrets.NPM_ORG_TOKEN }}"
          fi
          npm publish
