name: Test bin
on:
  pull_request:

jobs:
  latestDeploy:
    runs-on: ubuntu-latest
    name: "Test (node: ${{ matrix.node_version }})"
    strategy:
      matrix:
        node_version:
          - "16"
          - "17"
          - "18"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js (Github Packages)
        uses: actions/setup-node@v3.5.0
        with:
          node-version: "${{ matrix.node_version }}.x"
          cache: "npm"

      - name: Install node depencies
        run: npm install

      - name: Build (typescript)
        run: npm run build
